/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as BookRouteImport } from './routes/book'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GroundHandlingRouteImport } from './routes/ground-handling'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as PackageRouteImport } from './routes/package'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RentACarRouteImport } from './routes/rent-a-car'
import { Route as RentYourCarRouteImport } from './routes/rent-your-car'
import { Route as RentalProviderRouteImport } from './routes/rental-provider'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAddonServicesRouteImport } from './routes/admin.addon-services'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminFleetRouteImport } from './routes/admin.fleet'
import { Route as AdminGroundHandlingRouteImport } from './routes/admin.ground-handling'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminRentalApplicationsRouteImport } from './routes/admin.rental-applications'
import { Route as AdminRentalPartnersRouteImport } from './routes/admin.rental-partners'
import { Route as AdminRentalVehiclesRouteImport } from './routes/admin.rental-vehicles'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminSubscriptionPlansRouteImport } from './routes/admin.subscription-plans'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as GroundHandlingIndexRouteImport } from './routes/ground-handling.index'
import { Route as GroundHandlingFlightsRouteImport } from './routes/ground-handling.flights'
import { Route as GroundHandlingReportsRouteImport } from './routes/ground-handling.reports'
import { Route as GroundHandlingRequestsRouteImport } from './routes/ground-handling.requests'
import { Route as GroundHandlingServicesRouteImport } from './routes/ground-handling.services'
import { Route as GroundHandlingStaffRouteImport } from './routes/ground-handling.staff'
import { Route as GroundHandlingStatementsRouteImport } from './routes/ground-handling.statements'
import { Route as GroundHandlingTeamRouteImport } from './routes/ground-handling.team'
import { Route as GroundHandlingTravelersRouteImport } from './routes/ground-handling.travelers'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as OperatorFleetRouteImport } from './routes/operator.fleet'
import { Route as OperatorStatementsRouteImport } from './routes/operator.statements'
import { Route as OperatorTeamRouteImport } from './routes/operator.team'
import { Route as OperatorTripsRouteImport } from './routes/operator.trips'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerBookRouteImport } from './routes/partner.book'
import { Route as PartnerBookingsRouteImport } from './routes/partner.bookings'
import { Route as PartnerCapacityRouteImport } from './routes/partner.capacity'
import { Route as PartnerStatementsRouteImport } from './routes/partner.statements'
import { Route as PartnerTeamRouteImport } from './routes/partner.team'
import { Route as PartnerTermsRouteImport } from './routes/partner.terms'
import { Route as RentalProviderIndexRouteImport } from './routes/rental-provider.index'
import { Route as RentalProviderBookingsRouteImport } from './routes/rental-provider.bookings'
import { Route as RentalProviderTeamRouteImport } from './routes/rental-provider.team'
import { Route as RentalProviderVehiclesRouteImport } from './routes/rental-provider.vehicles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GroundHandlingRoute = GroundHandlingRouteImport.update({
  id: '/ground-handling',
  path: '/ground-handling',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageRoute = PackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RentACarRoute = RentACarRouteImport.update({
  id: '/rent-a-car',
  path: '/rent-a-car',
  getParentRoute: () => rootRouteImport,
} as any)
const RentYourCarRoute = RentYourCarRouteImport.update({
  id: '/rent-your-car',
  path: '/rent-your-car',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalProviderRoute = RentalProviderRouteImport.update({
  id: '/rental-provider',
  path: '/rental-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddonServicesRoute = AdminAddonServicesRouteImport.update({
  id: '/addon-services',
  path: '/addon-services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroundHandlingRoute = AdminGroundHandlingRouteImport.update({
  id: '/ground-handling',
  path: '/ground-handling',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRentalApplicationsRoute = AdminRentalApplicationsRouteImport.update({
  id: '/rental-applications',
  path: '/rental-applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRentalPartnersRoute = AdminRentalPartnersRouteImport.update({
  id: '/rental-partners',
  path: '/rental-partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRentalVehiclesRoute = AdminRentalVehiclesRouteImport.update({
  id: '/rental-vehicles',
  path: '/rental-vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionPlansRoute = AdminSubscriptionPlansRouteImport.update({
  id: '/subscription-plans',
  path: '/subscription-plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const GroundHandlingIndexRoute = GroundHandlingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroundHandlingRoute,
} as any)
const GroundHandlingFlightsRoute = GroundHandlingFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => GroundHandlingRoute,
} as any)
const GroundHandlingReportsRoute = GroundHandlingReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => GroundHandlingRoute,
} as any)
const GroundHandlingRequestsRoute = GroundHandlingRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => GroundHandlingRoute,
} as any)
const GroundHandlingServicesRoute = GroundHandlingServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => GroundHandlingRoute,
} as any)
const GroundHandlingStaffRoute = GroundHandlingStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => GroundHandlingRoute,
} as any)
const GroundHandlingStatementsRoute =
  GroundHandlingStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => GroundHandlingRoute,
  } as any)
const GroundHandlingTeamRoute = GroundHandlingTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => GroundHandlingRoute,
} as any)
const GroundHandlingTravelersRoute = GroundHandlingTravelersRouteImport.update({
  id: '/travelers',
  path: '/travelers',
  getParentRoute: () => GroundHandlingRoute,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorFleetRoute = OperatorFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorStatementsRoute = OperatorStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorTeamRoute = OperatorTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorTripsRoute = OperatorTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => OperatorRoute,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerBookRoute = PartnerBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerBookingsRoute = PartnerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerCapacityRoute = PartnerCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerStatementsRoute = PartnerStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerTeamRoute = PartnerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerTermsRoute = PartnerTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PartnerRoute,
} as any)
const RentalProviderIndexRoute = RentalProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RentalProviderRoute,
} as any)
const RentalProviderBookingsRoute = RentalProviderBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => RentalProviderRoute,
} as any)
const RentalProviderTeamRoute = RentalProviderTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => RentalProviderRoute,
} as any)
const RentalProviderVehiclesRoute = RentalProviderVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => RentalProviderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agency': typeof AgencyRoute
  '/book': typeof BookRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/ground-handling': typeof GroundHandlingRouteWithChildren
  '/my-bookings': typeof MyBookingsRoute
  '/operator': typeof OperatorRouteWithChildren
  '/package': typeof PackageRoute
  '/partner': typeof PartnerRouteWithChildren
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/rent-a-car': typeof RentACarRoute
  '/rent-your-car': typeof RentYourCarRoute
  '/rental-provider': typeof RentalProviderRouteWithChildren
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/admin/addon-services': typeof AdminAddonServicesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/ground-handling': typeof AdminGroundHandlingRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rental-applications': typeof AdminRentalApplicationsRoute
  '/admin/rental-partners': typeof AdminRentalPartnersRoute
  '/admin/rental-vehicles': typeof AdminRentalVehiclesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/subscription-plans': typeof AdminSubscriptionPlansRoute
  '/admin/team': typeof AdminTeamRoute
  '/ground-handling/flights': typeof GroundHandlingFlightsRoute
  '/ground-handling/reports': typeof GroundHandlingReportsRoute
  '/ground-handling/requests': typeof GroundHandlingRequestsRoute
  '/ground-handling/services': typeof GroundHandlingServicesRoute
  '/ground-handling/staff': typeof GroundHandlingStaffRoute
  '/ground-handling/statements': typeof GroundHandlingStatementsRoute
  '/ground-handling/team': typeof GroundHandlingTeamRoute
  '/ground-handling/travelers': typeof GroundHandlingTravelersRoute
  '/operator/fleet': typeof OperatorFleetRoute
  '/operator/statements': typeof OperatorStatementsRoute
  '/operator/team': typeof OperatorTeamRoute
  '/operator/trips': typeof OperatorTripsRoute
  '/partner/book': typeof PartnerBookRoute
  '/partner/bookings': typeof PartnerBookingsRoute
  '/partner/capacity': typeof PartnerCapacityRoute
  '/partner/statements': typeof PartnerStatementsRoute
  '/partner/team': typeof PartnerTeamRoute
  '/partner/terms': typeof PartnerTermsRoute
  '/rental-provider/bookings': typeof RentalProviderBookingsRoute
  '/rental-provider/team': typeof RentalProviderTeamRoute
  '/rental-provider/vehicles': typeof RentalProviderVehiclesRoute
  '/admin/': typeof AdminIndexRoute
  '/ground-handling/': typeof GroundHandlingIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/rental-provider/': typeof RentalProviderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/book': typeof BookRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/my-bookings': typeof MyBookingsRoute
  '/package': typeof PackageRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/rent-a-car': typeof RentACarRoute
  '/rent-your-car': typeof RentYourCarRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/admin/addon-services': typeof AdminAddonServicesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/ground-handling': typeof AdminGroundHandlingRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rental-applications': typeof AdminRentalApplicationsRoute
  '/admin/rental-partners': typeof AdminRentalPartnersRoute
  '/admin/rental-vehicles': typeof AdminRentalVehiclesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/subscription-plans': typeof AdminSubscriptionPlansRoute
  '/admin/team': typeof AdminTeamRoute
  '/ground-handling/flights': typeof GroundHandlingFlightsRoute
  '/ground-handling/reports': typeof GroundHandlingReportsRoute
  '/ground-handling/requests': typeof GroundHandlingRequestsRoute
  '/ground-handling/services': typeof GroundHandlingServicesRoute
  '/ground-handling/staff': typeof GroundHandlingStaffRoute
  '/ground-handling/statements': typeof GroundHandlingStatementsRoute
  '/ground-handling/team': typeof GroundHandlingTeamRoute
  '/ground-handling/travelers': typeof GroundHandlingTravelersRoute
  '/operator/fleet': typeof OperatorFleetRoute
  '/operator/statements': typeof OperatorStatementsRoute
  '/operator/team': typeof OperatorTeamRoute
  '/operator/trips': typeof OperatorTripsRoute
  '/partner/book': typeof PartnerBookRoute
  '/partner/bookings': typeof PartnerBookingsRoute
  '/partner/capacity': typeof PartnerCapacityRoute
  '/partner/statements': typeof PartnerStatementsRoute
  '/partner/team': typeof PartnerTeamRoute
  '/partner/terms': typeof PartnerTermsRoute
  '/rental-provider/bookings': typeof RentalProviderBookingsRoute
  '/rental-provider/team': typeof RentalProviderTeamRoute
  '/rental-provider/vehicles': typeof RentalProviderVehiclesRoute
  '/admin': typeof AdminIndexRoute
  '/ground-handling': typeof GroundHandlingIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/rental-provider': typeof RentalProviderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agency': typeof AgencyRoute
  '/book': typeof BookRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/ground-handling': typeof GroundHandlingRouteWithChildren
  '/my-bookings': typeof MyBookingsRoute
  '/operator': typeof OperatorRouteWithChildren
  '/package': typeof PackageRoute
  '/partner': typeof PartnerRouteWithChildren
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/rent-a-car': typeof RentACarRoute
  '/rent-your-car': typeof RentYourCarRoute
  '/rental-provider': typeof RentalProviderRouteWithChildren
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/admin/addon-services': typeof AdminAddonServicesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/ground-handling': typeof AdminGroundHandlingRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rental-applications': typeof AdminRentalApplicationsRoute
  '/admin/rental-partners': typeof AdminRentalPartnersRoute
  '/admin/rental-vehicles': typeof AdminRentalVehiclesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/subscription-plans': typeof AdminSubscriptionPlansRoute
  '/admin/team': typeof AdminTeamRoute
  '/ground-handling/flights': typeof GroundHandlingFlightsRoute
  '/ground-handling/reports': typeof GroundHandlingReportsRoute
  '/ground-handling/requests': typeof GroundHandlingRequestsRoute
  '/ground-handling/services': typeof GroundHandlingServicesRoute
  '/ground-handling/staff': typeof GroundHandlingStaffRoute
  '/ground-handling/statements': typeof GroundHandlingStatementsRoute
  '/ground-handling/team': typeof GroundHandlingTeamRoute
  '/ground-handling/travelers': typeof GroundHandlingTravelersRoute
  '/operator/fleet': typeof OperatorFleetRoute
  '/operator/statements': typeof OperatorStatementsRoute
  '/operator/team': typeof OperatorTeamRoute
  '/operator/trips': typeof OperatorTripsRoute
  '/partner/book': typeof PartnerBookRoute
  '/partner/bookings': typeof PartnerBookingsRoute
  '/partner/capacity': typeof PartnerCapacityRoute
  '/partner/statements': typeof PartnerStatementsRoute
  '/partner/team': typeof PartnerTeamRoute
  '/partner/terms': typeof PartnerTermsRoute
  '/rental-provider/bookings': typeof RentalProviderBookingsRoute
  '/rental-provider/team': typeof RentalProviderTeamRoute
  '/rental-provider/vehicles': typeof RentalProviderVehiclesRoute
  '/admin/': typeof AdminIndexRoute
  '/ground-handling/': typeof GroundHandlingIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/rental-provider/': typeof RentalProviderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agency'
    | '/book'
    | '/confirmation'
    | '/contact'
    | '/explore'
    | '/faq'
    | '/ground-handling'
    | '/my-bookings'
    | '/operator'
    | '/package'
    | '/partner'
    | '/payment'
    | '/privacy'
    | '/rent-a-car'
    | '/rent-your-car'
    | '/rental-provider'
    | '/search'
    | '/subscribe'
    | '/terms'
    | '/admin/addon-services'
    | '/admin/announcements'
    | '/admin/fleet'
    | '/admin/ground-handling'
    | '/admin/packages'
    | '/admin/partners'
    | '/admin/pricing'
    | '/admin/rental-applications'
    | '/admin/rental-partners'
    | '/admin/rental-vehicles'
    | '/admin/requests'
    | '/admin/subscription-plans'
    | '/admin/team'
    | '/ground-handling/flights'
    | '/ground-handling/reports'
    | '/ground-handling/requests'
    | '/ground-handling/services'
    | '/ground-handling/staff'
    | '/ground-handling/statements'
    | '/ground-handling/team'
    | '/ground-handling/travelers'
    | '/operator/fleet'
    | '/operator/statements'
    | '/operator/team'
    | '/operator/trips'
    | '/partner/book'
    | '/partner/bookings'
    | '/partner/capacity'
    | '/partner/statements'
    | '/partner/team'
    | '/partner/terms'
    | '/rental-provider/bookings'
    | '/rental-provider/team'
    | '/rental-provider/vehicles'
    | '/admin/'
    | '/ground-handling/'
    | '/operator/'
    | '/partner/'
    | '/rental-provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency'
    | '/book'
    | '/confirmation'
    | '/contact'
    | '/explore'
    | '/faq'
    | '/my-bookings'
    | '/package'
    | '/payment'
    | '/privacy'
    | '/rent-a-car'
    | '/rent-your-car'
    | '/search'
    | '/subscribe'
    | '/terms'
    | '/admin/addon-services'
    | '/admin/announcements'
    | '/admin/fleet'
    | '/admin/ground-handling'
    | '/admin/packages'
    | '/admin/partners'
    | '/admin/pricing'
    | '/admin/rental-applications'
    | '/admin/rental-partners'
    | '/admin/rental-vehicles'
    | '/admin/requests'
    | '/admin/subscription-plans'
    | '/admin/team'
    | '/ground-handling/flights'
    | '/ground-handling/reports'
    | '/ground-handling/requests'
    | '/ground-handling/services'
    | '/ground-handling/staff'
    | '/ground-handling/statements'
    | '/ground-handling/team'
    | '/ground-handling/travelers'
    | '/operator/fleet'
    | '/operator/statements'
    | '/operator/team'
    | '/operator/trips'
    | '/partner/book'
    | '/partner/bookings'
    | '/partner/capacity'
    | '/partner/statements'
    | '/partner/team'
    | '/partner/terms'
    | '/rental-provider/bookings'
    | '/rental-provider/team'
    | '/rental-provider/vehicles'
    | '/admin'
    | '/ground-handling'
    | '/operator'
    | '/partner'
    | '/rental-provider'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agency'
    | '/book'
    | '/confirmation'
    | '/contact'
    | '/explore'
    | '/faq'
    | '/ground-handling'
    | '/my-bookings'
    | '/operator'
    | '/package'
    | '/partner'
    | '/payment'
    | '/privacy'
    | '/rent-a-car'
    | '/rent-your-car'
    | '/rental-provider'
    | '/search'
    | '/subscribe'
    | '/terms'
    | '/admin/addon-services'
    | '/admin/announcements'
    | '/admin/fleet'
    | '/admin/ground-handling'
    | '/admin/packages'
    | '/admin/partners'
    | '/admin/pricing'
    | '/admin/rental-applications'
    | '/admin/rental-partners'
    | '/admin/rental-vehicles'
    | '/admin/requests'
    | '/admin/subscription-plans'
    | '/admin/team'
    | '/ground-handling/flights'
    | '/ground-handling/reports'
    | '/ground-handling/requests'
    | '/ground-handling/services'
    | '/ground-handling/staff'
    | '/ground-handling/statements'
    | '/ground-handling/team'
    | '/ground-handling/travelers'
    | '/operator/fleet'
    | '/operator/statements'
    | '/operator/team'
    | '/operator/trips'
    | '/partner/book'
    | '/partner/bookings'
    | '/partner/capacity'
    | '/partner/statements'
    | '/partner/team'
    | '/partner/terms'
    | '/rental-provider/bookings'
    | '/rental-provider/team'
    | '/rental-provider/vehicles'
    | '/admin/'
    | '/ground-handling/'
    | '/operator/'
    | '/partner/'
    | '/rental-provider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgencyRoute: typeof AgencyRoute
  BookRoute: typeof BookRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  GroundHandlingRoute: typeof GroundHandlingRouteWithChildren
  MyBookingsRoute: typeof MyBookingsRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  PackageRoute: typeof PackageRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PaymentRoute: typeof PaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  RentACarRoute: typeof RentACarRoute
  RentYourCarRoute: typeof RentYourCarRoute
  RentalProviderRoute: typeof RentalProviderRouteWithChildren
  SearchRoute: typeof SearchRoute
  SubscribeRoute: typeof SubscribeRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ground-handling': {
      id: '/ground-handling'
      path: '/ground-handling'
      fullPath: '/ground-handling'
      preLoaderRoute: typeof GroundHandlingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package': {
      id: '/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof PackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-a-car': {
      id: '/rent-a-car'
      path: '/rent-a-car'
      fullPath: '/rent-a-car'
      preLoaderRoute: typeof RentACarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-your-car': {
      id: '/rent-your-car'
      path: '/rent-your-car'
      fullPath: '/rent-your-car'
      preLoaderRoute: typeof RentYourCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental-provider': {
      id: '/rental-provider'
      path: '/rental-provider'
      fullPath: '/rental-provider'
      preLoaderRoute: typeof RentalProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/addon-services': {
      id: '/admin/addon-services'
      path: '/addon-services'
      fullPath: '/admin/addon-services'
      preLoaderRoute: typeof AdminAddonServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ground-handling': {
      id: '/admin/ground-handling'
      path: '/ground-handling'
      fullPath: '/admin/ground-handling'
      preLoaderRoute: typeof AdminGroundHandlingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rental-applications': {
      id: '/admin/rental-applications'
      path: '/rental-applications'
      fullPath: '/admin/rental-applications'
      preLoaderRoute: typeof AdminRentalApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rental-partners': {
      id: '/admin/rental-partners'
      path: '/rental-partners'
      fullPath: '/admin/rental-partners'
      preLoaderRoute: typeof AdminRentalPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rental-vehicles': {
      id: '/admin/rental-vehicles'
      path: '/rental-vehicles'
      fullPath: '/admin/rental-vehicles'
      preLoaderRoute: typeof AdminRentalVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscription-plans': {
      id: '/admin/subscription-plans'
      path: '/subscription-plans'
      fullPath: '/admin/subscription-plans'
      preLoaderRoute: typeof AdminSubscriptionPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ground-handling/': {
      id: '/ground-handling/'
      path: '/'
      fullPath: '/ground-handling/'
      preLoaderRoute: typeof GroundHandlingIndexRouteImport
      parentRoute: typeof GroundHandlingRoute
    }
    '/ground-handling/flights': {
      id: '/ground-handling/flights'
      path: '/flights'
      fullPath: '/ground-handling/flights'
      preLoaderRoute: typeof GroundHandlingFlightsRouteImport
      parentRoute: typeof GroundHandlingRoute
    }
    '/ground-handling/reports': {
      id: '/ground-handling/reports'
      path: '/reports'
      fullPath: '/ground-handling/reports'
      preLoaderRoute: typeof GroundHandlingReportsRouteImport
      parentRoute: typeof GroundHandlingRoute
    }
    '/ground-handling/requests': {
      id: '/ground-handling/requests'
      path: '/requests'
      fullPath: '/ground-handling/requests'
      preLoaderRoute: typeof GroundHandlingRequestsRouteImport
      parentRoute: typeof GroundHandlingRoute
    }
    '/ground-handling/services': {
      id: '/ground-handling/services'
      path: '/services'
      fullPath: '/ground-handling/services'
      preLoaderRoute: typeof GroundHandlingServicesRouteImport
      parentRoute: typeof GroundHandlingRoute
    }
    '/ground-handling/staff': {
      id: '/ground-handling/staff'
      path: '/staff'
      fullPath: '/ground-handling/staff'
      preLoaderRoute: typeof GroundHandlingStaffRouteImport
      parentRoute: typeof GroundHandlingRoute
    }
    '/ground-handling/statements': {
      id: '/ground-handling/statements'
      path: '/statements'
      fullPath: '/ground-handling/statements'
      preLoaderRoute: typeof GroundHandlingStatementsRouteImport
      parentRoute: typeof GroundHandlingRoute
    }
    '/ground-handling/team': {
      id: '/ground-handling/team'
      path: '/team'
      fullPath: '/ground-handling/team'
      preLoaderRoute: typeof GroundHandlingTeamRouteImport
      parentRoute: typeof GroundHandlingRoute
    }
    '/ground-handling/travelers': {
      id: '/ground-handling/travelers'
      path: '/travelers'
      fullPath: '/ground-handling/travelers'
      preLoaderRoute: typeof GroundHandlingTravelersRouteImport
      parentRoute: typeof GroundHandlingRoute
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/fleet': {
      id: '/operator/fleet'
      path: '/fleet'
      fullPath: '/operator/fleet'
      preLoaderRoute: typeof OperatorFleetRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/statements': {
      id: '/operator/statements'
      path: '/statements'
      fullPath: '/operator/statements'
      preLoaderRoute: typeof OperatorStatementsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/team': {
      id: '/operator/team'
      path: '/team'
      fullPath: '/operator/team'
      preLoaderRoute: typeof OperatorTeamRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/trips': {
      id: '/operator/trips'
      path: '/trips'
      fullPath: '/operator/trips'
      preLoaderRoute: typeof OperatorTripsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/book': {
      id: '/partner/book'
      path: '/book'
      fullPath: '/partner/book'
      preLoaderRoute: typeof PartnerBookRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/bookings': {
      id: '/partner/bookings'
      path: '/bookings'
      fullPath: '/partner/bookings'
      preLoaderRoute: typeof PartnerBookingsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/capacity': {
      id: '/partner/capacity'
      path: '/capacity'
      fullPath: '/partner/capacity'
      preLoaderRoute: typeof PartnerCapacityRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/statements': {
      id: '/partner/statements'
      path: '/statements'
      fullPath: '/partner/statements'
      preLoaderRoute: typeof PartnerStatementsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/team': {
      id: '/partner/team'
      path: '/team'
      fullPath: '/partner/team'
      preLoaderRoute: typeof PartnerTeamRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/terms': {
      id: '/partner/terms'
      path: '/terms'
      fullPath: '/partner/terms'
      preLoaderRoute: typeof PartnerTermsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/rental-provider/': {
      id: '/rental-provider/'
      path: '/'
      fullPath: '/rental-provider/'
      preLoaderRoute: typeof RentalProviderIndexRouteImport
      parentRoute: typeof RentalProviderRoute
    }
    '/rental-provider/bookings': {
      id: '/rental-provider/bookings'
      path: '/bookings'
      fullPath: '/rental-provider/bookings'
      preLoaderRoute: typeof RentalProviderBookingsRouteImport
      parentRoute: typeof RentalProviderRoute
    }
    '/rental-provider/team': {
      id: '/rental-provider/team'
      path: '/team'
      fullPath: '/rental-provider/team'
      preLoaderRoute: typeof RentalProviderTeamRouteImport
      parentRoute: typeof RentalProviderRoute
    }
    '/rental-provider/vehicles': {
      id: '/rental-provider/vehicles'
      path: '/vehicles'
      fullPath: '/rental-provider/vehicles'
      preLoaderRoute: typeof RentalProviderVehiclesRouteImport
      parentRoute: typeof RentalProviderRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAddonServicesRoute: typeof AdminAddonServicesRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminGroundHandlingRoute: typeof AdminGroundHandlingRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRentalApplicationsRoute: typeof AdminRentalApplicationsRoute
  AdminRentalPartnersRoute: typeof AdminRentalPartnersRoute
  AdminRentalVehiclesRoute: typeof AdminRentalVehiclesRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSubscriptionPlansRoute: typeof AdminSubscriptionPlansRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAddonServicesRoute: AdminAddonServicesRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminGroundHandlingRoute: AdminGroundHandlingRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRentalApplicationsRoute: AdminRentalApplicationsRoute,
  AdminRentalPartnersRoute: AdminRentalPartnersRoute,
  AdminRentalVehiclesRoute: AdminRentalVehiclesRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSubscriptionPlansRoute: AdminSubscriptionPlansRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GroundHandlingRouteChildren {
  GroundHandlingFlightsRoute: typeof GroundHandlingFlightsRoute
  GroundHandlingReportsRoute: typeof GroundHandlingReportsRoute
  GroundHandlingRequestsRoute: typeof GroundHandlingRequestsRoute
  GroundHandlingServicesRoute: typeof GroundHandlingServicesRoute
  GroundHandlingStaffRoute: typeof GroundHandlingStaffRoute
  GroundHandlingStatementsRoute: typeof GroundHandlingStatementsRoute
  GroundHandlingTeamRoute: typeof GroundHandlingTeamRoute
  GroundHandlingTravelersRoute: typeof GroundHandlingTravelersRoute
  GroundHandlingIndexRoute: typeof GroundHandlingIndexRoute
}

const GroundHandlingRouteChildren: GroundHandlingRouteChildren = {
  GroundHandlingFlightsRoute: GroundHandlingFlightsRoute,
  GroundHandlingReportsRoute: GroundHandlingReportsRoute,
  GroundHandlingRequestsRoute: GroundHandlingRequestsRoute,
  GroundHandlingServicesRoute: GroundHandlingServicesRoute,
  GroundHandlingStaffRoute: GroundHandlingStaffRoute,
  GroundHandlingStatementsRoute: GroundHandlingStatementsRoute,
  GroundHandlingTeamRoute: GroundHandlingTeamRoute,
  GroundHandlingTravelersRoute: GroundHandlingTravelersRoute,
  GroundHandlingIndexRoute: GroundHandlingIndexRoute,
}

const GroundHandlingRouteWithChildren = GroundHandlingRoute._addFileChildren(
  GroundHandlingRouteChildren,
)

interface OperatorRouteChildren {
  OperatorFleetRoute: typeof OperatorFleetRoute
  OperatorStatementsRoute: typeof OperatorStatementsRoute
  OperatorTeamRoute: typeof OperatorTeamRoute
  OperatorTripsRoute: typeof OperatorTripsRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorFleetRoute: OperatorFleetRoute,
  OperatorStatementsRoute: OperatorStatementsRoute,
  OperatorTeamRoute: OperatorTeamRoute,
  OperatorTripsRoute: OperatorTripsRoute,
  OperatorIndexRoute: OperatorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

interface PartnerRouteChildren {
  PartnerBookRoute: typeof PartnerBookRoute
  PartnerBookingsRoute: typeof PartnerBookingsRoute
  PartnerCapacityRoute: typeof PartnerCapacityRoute
  PartnerStatementsRoute: typeof PartnerStatementsRoute
  PartnerTeamRoute: typeof PartnerTeamRoute
  PartnerTermsRoute: typeof PartnerTermsRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerBookRoute: PartnerBookRoute,
  PartnerBookingsRoute: PartnerBookingsRoute,
  PartnerCapacityRoute: PartnerCapacityRoute,
  PartnerStatementsRoute: PartnerStatementsRoute,
  PartnerTeamRoute: PartnerTeamRoute,
  PartnerTermsRoute: PartnerTermsRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

interface RentalProviderRouteChildren {
  RentalProviderBookingsRoute: typeof RentalProviderBookingsRoute
  RentalProviderTeamRoute: typeof RentalProviderTeamRoute
  RentalProviderVehiclesRoute: typeof RentalProviderVehiclesRoute
  RentalProviderIndexRoute: typeof RentalProviderIndexRoute
}

const RentalProviderRouteChildren: RentalProviderRouteChildren = {
  RentalProviderBookingsRoute: RentalProviderBookingsRoute,
  RentalProviderTeamRoute: RentalProviderTeamRoute,
  RentalProviderVehiclesRoute: RentalProviderVehiclesRoute,
  RentalProviderIndexRoute: RentalProviderIndexRoute,
}

const RentalProviderRouteWithChildren = RentalProviderRoute._addFileChildren(
  RentalProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgencyRoute: AgencyRoute,
  BookRoute: BookRoute,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  GroundHandlingRoute: GroundHandlingRouteWithChildren,
  MyBookingsRoute: MyBookingsRoute,
  OperatorRoute: OperatorRouteWithChildren,
  PackageRoute: PackageRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PaymentRoute: PaymentRoute,
  PrivacyRoute: PrivacyRoute,
  RentACarRoute: RentACarRoute,
  RentYourCarRoute: RentYourCarRoute,
  RentalProviderRoute: RentalProviderRouteWithChildren,
  SearchRoute: SearchRoute,
  SubscribeRoute: SubscribeRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
